SLURM_SUBMIT_DIR=/home/kyuminkim/project/cli_things/scripts
CUDA_HOME=
CUDA_VISIBLE_DEVICES=0,1
CUDA_VERSION=
0: n58.gasi-cluster
0: /home/kyuminkim/project/cli_things/scripts
0: 2024. 08. 12. (월) 04:25:32 KST
Start
conda PATH
source /home/kyuminkim/anaconda3/etc/profile.d/conda.sh
conda activate torchtune
W0812 07:28:17.263000 139624291055424 torch/distributed/run.py:757] 
W0812 07:28:17.263000 139624291055424 torch/distributed/run.py:757] *****************************************
W0812 07:28:17.263000 139624291055424 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0812 07:28:17.263000 139624291055424 torch/distributed/run.py:757] *****************************************
[W socket.cpp:464] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:464] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
[E socket.cpp:500] [c10d] The server socket has failed to listen on any local network address.
Running with torchrun...
Traceback (most recent call last):
  File "/home/kyuminkim/anaconda3/envs/torchtune/bin/tune", line 8, in <module>
    sys.exit(main())
  File "/home/kyuminkim/project/torchtune/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/kyuminkim/project/torchtune/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/kyuminkim/project/torchtune/torchtune/_cli/run.py", line 177, in _run_cmd
    self._run_distributed(args)
  File "/home/kyuminkim/project/torchtune/torchtune/_cli/run.py", line 88, in _run_distributed
    run(args)
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 254, in launch_agent
    result = agent.run()
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 733, in run
    result = self._invoke_run(role)
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 870, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 705, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 548, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/kyuminkim/anaconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
2024. 08. 12. (월) 07:28:25 KST
conda deactivate torchtune

ArgumentError: deactivate does not accept arguments
remainder_args: ['torchtune']


             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
            337011 A100-80GB torhtune kyuminki  R    3:04:31      1 n58
##### END #####
